### ISSUE TITLE
Not works on openSUSE 13.2(64bits)

### ISSUE THREAD

**Issue by valbendan** [bbchung/clighter#17]
It's seems not works on openSUSE 13.2.
My vim version is the default version of openSUSE,
(VIM - Vi IMproved 7.4 (2013 Aug 10)
Included patches: 1-461
Compiled by 'http://www.opensuse.org/')

I use :vim test.c with clighter start:
It shows like the below:

  1 0,0-1All
~                                                                         
~                                         
~                                                                         
"test.c" [New File]                                     

I can't input anything at all, and the CPU usage is 100%!

**Comment by mbiberhofer** [comment]
I can confirm that this is plugin also has an issue on OpenSUSE 13.2 32bit, though I can't reproduce the CPU consumption. Versions:
CLANG 13.5.0
VIM 7.4 (Patches 1-461)

**Comment by mbiberhofer** [comment]
Okay, I just solved my issue by fetching the official LLVM/CLANG OpenSUSE 3.6.0 package from llvm.org and set my clighter_libclang_file to the libclang.so shipped with the package -- it looks like the openSUSE libclang breaks clighter, even though it's v3.5.

**Comment by bbchung** [comment]
Thanks for your testing. Issue closed.
