### ISSUE TITLE
Clarify License, AUR package

### ISSUE THREAD

**Issue by olantwin** [bbchung/clighter#19]
Dear bbchung,

I have created a build script for Arch Linux, where clighter woks beautifully.
The script is hosted in the AUR at https://aur.archlinux.org/packages/vim-clighter-git/ and automates installation for arch users. Feel free to link to it in the installation instructions, if you want.

However this also brings me to the issue. Could you please clarify the license of clighter? E.g by adding a license file or by adding some boilerplate to each file. Currently it is unclear whether others are allowed to use your code/plugin, as by default it is not open-source/free.

Keep up the great work on the plugin,

All the best, 

olantwin

**Comment by bbchung** [comment]
Hi olantwin,

Thanks for your using and recommendation of clighter.
I have add the license for clighter, and it's under GPL V3.

**Comment by olantwin** [comment]
Great, thank you!
