### ISSUE TITLE
Delay between cursor move and highlight

### ISSUE THREAD

**Issue by matthiasvegh** [bbchung/clighter#20]
About two weeks ago, the moment the cursor was placed above a symbol, the symbol was highlighted, along with all other references to it in the current file. This behaviour is still present, but now there is a 2-3s delay between placing the cursor on the symbol and the highlighting.

I'm not sure if this is intentional, but I'd sure like to see the old behaviour back. If it helps, the last version I saw where this was immediate was around two weeks ago. I can search for the commit that introduced the delay if you want.

Cheers.

**Comment by bbchung** [comment]
Hi matthiasvegh,

The reason to introduce the delay(updatetime) is to simulate visual studio behavior and save cpu time.
However you can let g:clighter_cursor_hl_mode=1 to play with the old behavior in the newest version, update and enjoy.
