### ISSUE TITLE
Flags for header files are missing

### ISSUE THREAD

**Issue by matthiasvegh** [bbchung/clighter#21]
compile_commands.jsons generated by cmake for instance, do not add flags for headers, as they are not compiled directly. For this reason, the highlighting is incomplete for hpps.

I'd like to see a heuristic similiar to the one implemented [here](https://github.com/martong/ycm_extra_conf.jsondb). The basic notion that could be applied is that if the file is a header, attempt to find a corresponding source file. If one is present, inherit the flags from it. If not, find a source file that includes the directory within which the header is located. If the header is a new one however, perhaps uniting all the compile flags present would be the best approach.

**Comment by bbchung** [comment]
Heuristic search has been implemented in last commit. It's implemented basically according to your post, but some difference is in it.
