### ISSUE TITLE
High CPU usage under some circumstances

### ISSUE THREAD

**Issue by Hexcles** [bbchung/clighter#22]
e.g.
Open a cpp source file and then immediately open a help window (by typing `:help WHATEVER`). Then vim process will take 100% CPU (and does not seem to stop within reasonable time). However, if you close the help window, the CPU usage will drop to normal soon. And if you wait for some time before open the help, it seems this phenomenon will not happen.

**Comment by bbchung** [comment]
I have confirmed this bug, the behavior is just like you said, and I have fix it.
