### ISSUE TITLE
Add / Reenable setting of flags from function

### ISSUE THREAD

**Issue by matthiasvegh** [bbchung/clighter#24]
Hi,

Recently (https://github.com/bbchung/clighter/commit/4699a2727d4ea41aaa120c6083e9921a727f6bc1) the SetCompileArgs was removed in favour of using compile_commands.json. While this is certainly preferred if such a file is available or if Clighter is used without any other clang based vim plugin, but if clighter is used with other plugins, it would be very helpful if it was possible to programatically (ie.: from another script) set the compiler arguments. In my case I want to be able to synchronize the flags between YouCompleteMe and Clighter, but other plugins exist where this would be helpful, such as vim-rtags.

So ideally SetCompileArgs (or any other method usable from a vimscript) could be used on a per buffer basis.

An example of the mechanism that would be used to tell clighter what flags to use is available [here](https://github.com/matthiasvegh/ycmlighter/blob/master/autoload/ycmlighter.vim#L29). This coincidentally is a plugin that depended heavily on the presence of the SetCompileArgs function.

Thanks a lot for your time,

matthiasvegh

**Comment by bbchung** [comment]
I add a g:clighter_compile_args option, but it only load one time at start in e4170275bdf246b31b7f41f2b3947e6ab6665f64
