### ISSUE TITLE
Adding compilation database breaks some highlighting

### ISSUE THREAD

**Issue by octol** [bbchung/clighter#26]
Without a compilation database only some highlights works. When I create a compilation database everything seem to work at first. However, template types in functions stop working.

Without compilation databse
![without-compilation-database](https://cloud.githubusercontent.com/assets/1894054/7098208/8b036ca0-dfd5-11e4-8a3b-9b8b11fa5062.png)

With compilation database
![with-compilation-database](https://cloud.githubusercontent.com/assets/1894054/7098209/8c6a1f58-dfd5-11e4-8fa8-70541f2b63f4.png)

Here the `It` stops being highlighted when I add a compilation database.

**Comment by bbchung** [comment]
In my test, it works normally, plz post your compile_commands.json and show me result of command ClighterShowInfo

**Comment by octol** [comment]
Here is a cut down independent example. Notice that there are two issues here, the not-instantiated function is not highlighted, but has correct `It` highlight in arguments. The instantiated function is correctly highlighted but doesn't highlight `It`.

![template_function](https://cloud.githubusercontent.com/assets/1894054/7101099/e6f86e80-e03d-11e4-89df-602ab81d1f27.png)

ClighterShowInfo:

![clighterinfo](https://cloud.githubusercontent.com/assets/1894054/7101100/ed2940f4-e03d-11e4-9832-71628ddb2b51.png)

compile_commands.json:

```json
[
    {
        "command": "clang++ -std=c++1y -c -o main.o main.cpp", 
        "directory": "/tmp/clighter_test", 
        "file": "/tmp/clighter_test/main.cpp"
    } 
]
```

**Comment by bbchung** [comment]
Ok, I found that  different compile args cause different cursor kind, so we see the different result. It seems need a new mechanism to get a higher coverage and flexible highlight result, and it's not hard.

**Comment by bbchung** [comment]
Try the newest commit, and notice that some syntax group define was changed

**Comment by octol** [comment]
Looks fixed on this side :)
