### ISSUE TITLE
Compilation flags not found if quoted in compilation database

### ISSUE THREAD

**Issue by petersohn** [bbchung/clighter#28]
Since I am not using cmake, I use my own script to generate the compilation database. This script quotes each argument of the command.

    {
        "directory": "/home/eszabpt/workspace/sokoban/src",
        "command": "clang++ '-std=c++14' '-Wall' '-Wextra' '-Werror' '-ftemplate-backtrace-limit=0' '-I../src' '-I../cpp-util/include' '-c' '-o' 'ChokePointFinder.o' 'ChokePointFinder.cpp'",
        "file": "/home/eszabpt/workspace/sokoban/src/ChokePointFinder.cpp"
    }

This should work, as the command above is a valid shell command to compile the file. However, clighter doesn't find the compile flags for this file. If I remove the quotes, it works well.

**Comment by bbchung** [comment]
plz check the format of your compile_commands.json
http://clang.llvm.org/docs/JSONCompilationDatabase.html

**Comment by petersohn** [comment]
I checked and it is correct, as you can see on my example snippet. It works well with other tools that use compilation database, such as YouCompleteMe. If I copy-paste the command into the terminal, it still works. It also works with clighter if I remove the apostrophes. The problem is not with the compilation database, but that clighter somehow fails to parse it if the command arguments are enclosed in apostrophes (which is correct in a shell command).

**Comment by bbchung** [comment]
ok, I will check it, thanks for your using

**Comment by bbchung** [comment]
try 794b1919d8b291155345cfa962309203368cd851, it should fix the apostrophes issue

**Comment by bbchung** [comment]
should be fixed
