### ISSUE TITLE
Compilation flags parsed wrong when argument and value are in different parameters

### ISSUE THREAD

**Issue by petersohn** [bbchung/clighter#29]
If I have a compilation database with the following flag:

    -I /some/path

I get the following values in the compilation flags instead:

    -I -I

I did a bisect and the error was introduced in the following commit:

     commit 794b1919d8b291155345cfa962309203368cd851
     Author: bbchung <afafaf4@gmail.com>
     Date:   Fri May 22 17:57:23 2015 +0800

        re implement compilation_database.py

**Comment by bbchung** [comment]
should be fixed
