### ISSUE TITLE
`ClighterShowInfo` gives wrong results when file is opened from command line

### ISSUE THREAD

**Issue by petersohn** [bbchung/clighter#32]
If I open a file from the command line, like this:

    vim path/to/file.cpp

And then issue the `ClighterShowInfo` command, then the `Current context` and `Compile args` parameters are displayed as `none`. Despite this, highlighting seems to work (I did not test it thoroughly though).

Changing the buffer then changing it back solves the problem.

**Comment by bbchung** [comment]
I can't reproduce this issue, does it happen randomly?

**Comment by petersohn** [comment]
Hmm, it seems that it only occurs if I also use the [jistr/vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs) plugin and set it to automatically open a nerdtree window at startup.

**Comment by bbchung** [comment]
If the nerdtree window is the current window, it's expected

**Comment by petersohn** [comment]
When I start vim this way, the current window is the cpp file, and yet the debug info shows wrong result until I switch buffers back and forth.

**Comment by bbchung** [comment]
current context information has been removed
