### ISSUE TITLE
name 'vim' is not defined

### ISSUE THREAD

**Issue by lisdude** [bbchung/clighter#36]
Opening Vim is giving a traceback in clighter#Enable and saying the name 'vim' is not defined.

Adding "py import vim" at the top of autoload/clighter.vim seems to fix the issue. I don't really know anything about Vimscript or Python, though, so I don't know if that's a horrible thing to do or not.

**Comment by bbchung** [comment]
have you upgraded clighter? what os you use

**Comment by lisdude** [comment]
I'm at the latest commit of clighter. For everything else...

OS: OS X 10.10.3
Python: 2.7.10
Vim: 7.4.738

The actual error text (without the press enter to continues) is:

Error detected while processing function clighter#Enable:
line 22:
Traceback (most recent call last):
Error detected while processing function clighter#Enable:
line 22:
File "<string>", line 1, in <module>
Error detected while processing function clighter#Enable:
line 22:
NameError: name 'vim' is not defined

**Comment by bbchung** [comment]
fixed
