### ISSUE TITLE
Works lika a charm on Windows, except: autoload/clighter.vim line 83

### ISSUE THREAD

**Issue by muellan** [bbchung/clighter#37]
Maybe you could do us poor Windows people a favor and add a platform specific fix
```if has("win32") || has("win16") || has("win64")```
then one needs to substitute all backslashes in the result of ```fnamemodify(expand(...)...)``` with slashes or otherwise one ends up with escape sequences in the string.
I modified autoload/clighter.vim line 83 to
```
au BufDelete,BufWipeout * exe 'py clang_service.ClangService().unregister("'. substitute(fnamemodify(expand("<afile>"), ":p"), '\', '/', 'g') . '")'
```

**Comment by bbchung** [comment]
fixed with your recommendation
