### ISSUE TITLE
Symbol highlighting get stuck upon window change

### ISSUE THREAD

**Issue by petersohn** [bbchung/clighter#38]
To reproduce the issue, follow these steps:

1. Move the cursor somewhere where a symbol is highlighted.
2. Move to another window or tab showing another source file, somewhere where no symbol is highlighted.
3. Move back to the previous window/tab.

Now the highlighting on the original window is stuck. Wherever I move the cursor the original highlighting remains until I make a change in the source (or force clighter to refresh some other way, such as by reloading the file).

The problem doesn't occur if when I return to the original window a symbol is highlighted on the second window, or the second window is not a source file.

**Comment by bbchung** [comment]
should be fixed, update plugin

**Comment by petersohn** [comment]
Thanks, it works now.
