### ISSUE TITLE
path to compile database

### ISSUE THREAD

**Issue by laxitg** [bbchung/clighter#39]
Hi,

I wanted to request a feature, which shouldn't be very complicated (imho). As of now compile_command.json is parsed if it's in current working directory, but most of the projects would have a seperate build folder (atleast projects which have moved past make) which contains the aforementioned file. So, if a variable can be set to point to directory containing compile_commmand.json. 

Thanking You,
Laxit Gavshinde

**Comment by bbchung** [comment]
good suggestion

**Comment by bbchung** [comment]
not implement, because the compilation data base path will be project based, clighter can't provide option for each project

**Comment by laxitg** [comment]
Hi,

I know it would be different for every project, but very few cases will have the the build files in the same directory, hence i expect this feature might not get used a lot. If a option for list of relative paths from the working directory is provided like the envirnoment variable PATH could be useful. Or may be searching for the build directory upwards from current directory could do the job.

I know it doesn't cover all the cases but it does expand the cases and usability. If you are ok with it i can create a PR with the fix.

**Comment by bbchung** [comment]
it's ok, of course
