### ISSUE TITLE
Makes the cursor movements sluggish

### ISSUE THREAD

**Issue by sittim** [bbchung/clighter#44]
I love the clighter, but it makes the cursor movements very slow in NeoVIM.  My configuration is default, is there anything I can try to make cursor movements smooth?  I was looking at the configurations, and do not see anything that can be applicable to speeding thing up.

**Comment by bbchung** [comment]
Hi, sittim

clighter is use python heavily, and I guess the delay is caused by NeoVim's new python architecture, so i can't fix it.
clighter may official support neovim's new plugin architecture while neovim's api is more stabled

**Comment by sittim** [comment]
OK, yes, actually I was wondering if it is possible to run the clighter asynchronously in neovim, that would be the ultimate.  Anyway, otherwise your plug-in is awesome, I love it...

**Comment by bbchung** [comment]
I add a option g:clighter_highlight_mode to the plugin, plz set it to 0 and you will not feel laggy, however, the screen update will be slower

**Comment by sittim** [comment]
OK, that works perfect, thank you....
